---
image: ubuntu:rolling

check-job:
  tags:
    - arm64

  script:
    - apt-get update
    - apt-get install -y make python3 python3-construct python3-yaml
      python3-chardet python3-jsonschema u-boot-tools python3-requests
      uuid-runtime python3-packaging device-tree-compiler bsdextrautils
      python3-pip swig yamllint flake8 git mypy pylint
    - pip3 install --break-system-packages dtschema
    - make -k check

  artifacts:
    when: always

    paths:
      - test-*.log

doc-job:
  tags:
    - arm64

  script:
    - apt-get update
    - apt-get install -y make pandoc texlive-latex-base
      texlive-latex-recommended texlive-latex-extra
    - make doc

  artifacts:
    paths:
      - README.pdf
