#!/bin/bash
set -eu -o pipefail

# Unit test for identify.py.
# Usage: test-identify [keep]
# We keep our temporary folder when `keep' is specified.

# Redirect all output to a log in current folder.
# Keep stdout on fd 3.
bn=$(basename "$0")
log="$bn.log"
exec 3>&1 >"$log" 2>&1
set -x

echo -n 'Testing identify... ' >&3
trap 'echo "ERROR! (see $log)" >&3' ERR

# Make sure identify.py is in the path.
me=$(realpath "$0")
here="${me%/*}"
export PATH="$here/..:$PATH"

# Temporary folder.
if [ "${1:-unset}" == keep ]; then
	tmp=$(mktemp -d "$(basename "$0").XXX")
else
	tmp=$(mktemp -d)
	trap 'rm -fr "$tmp"' EXIT
fi

data="$here/data/$(basename "$0")"
out="$tmp/out"

echo -n 'none, ' >&3
if identify.py |& tee "$out"; then
	false
fi

grep -q Unknown "$out"

echo -n 'ir1.0 bet-0, ' >&3
identify.py --dir "$data/v21.05_0.8_BETA-0" |& tee "$out"
grep -q 'SystemReady IR v1.0' "$out"

identify.py --dir "$data/v21.05_0.8_BETA-0" --ebbr-seq |& tee "$out"
grep -q 'ACS-IR v21.05_0.8_BETA-0' "$out"

echo -n 'ir1.0 bet-1, ' >&3
identify.py --dir "$data/v21.07_0.9_BETA" |& tee "$out"
grep -q 'SystemReady IR v1.0' "$out"

identify.py --dir "$data/v21.07_0.9_BETA" --ebbr-seq |& tee "$out"
grep -q 'ACS-IR v21.07_0.9_BETA' "$out"

echo -n 'ir1.1, ' >&3
identify.py --dir "$data/v21.09_1.0" |& tee "$out"
grep -q 'SystemReady IR v1.1' "$out"

identify.py --dir "$data/v21.09_1.0" --ebbr-seq |& tee "$out"
grep -q 'ACS-IR v21.09_1.0' "$out"

echo 'ok.' >&3
