#!/bin/bash
set -eu -o pipefail

# Unit test for guid-tool.py.
# Usage: test-guid-tool [keep]
# We keep our temporary folder when `keep' is specified.

# Redirect all output to a log in current folder.
# Keep stdout on fd 3.
bn=$(basename "$0")
log="$bn.log"
exec 3>&1 >"$log" 2>&1
set -x

echo -n 'Testing guid tool... ' >&3
trap 'echo "ERROR! (see $log)" >&3' ERR

# Make sure guid-tool.py is in the path.
me=$(realpath "$0")
here="${me%/*}"
export PATH="$here/..:$PATH"

# Temporary folder.
if [ "${1:-unset}" == keep ]; then
	tmp=$(mktemp -d "$(basename "$0").XXX")
else
	tmp=$(mktemp -d)
	trap 'rm -fr "$tmp"' EXIT
fi

out="$tmp/out"
guid-tool.py 12345678-1234-1234-1234-56789abcdef0 |& tee "$out"
grep -q Unknown "$out"
echo -n 'unknown guid not recognized, ' >&3

guid-tool.py ae13ff2d-9ad4-4e25-9ac8-6d80b3b22147 |& tee "$out"
grep -q 'EFI_FIRMWARE_IMAGE_TYPE_UBOOT_FIT_GUID' "$out"
echo -n 'known guid recognized, ' >&3

if guid-tool.py ABC |& tee "$out"; then
	false
fi

grep -q Invalid "$out"
echo -n 'invalid guid rejected, ' >&3

echo 'ok.' >&3
