#!/bin/bash
set -eu -o pipefail

# Unit test for ethernet-parser.py.
# Usage: test-ethernet [keep]
# We keep our temporary folder when `keep' is specified.

# Redirect all output to a log in current folder.
# Keep stdout on fd 3.
bn=$(basename "$0")
log="$bn.log"
exec 3>&1 >"$log" 2>&1
set -x

echo -n 'Testing ethernet-parser... ' >&3
trap 'echo "ERROR! (see $log)" >&3' ERR

# Make sure ethernet-parser.py is in the path.
me=$(realpath "$0")
here="${me%/*}"
export PATH="$here/..:$PATH"

# Temporary folder.
if [ "${1:-unset}" == keep ]; then
	tmp=$(mktemp -d "$(basename "$0").XXX")
else
	tmp=$(mktemp -d)
	trap 'rm -fr "$tmp"' EXIT
fi

data="$here/data/$(basename "$0")"
out="$tmp/out"

echo -n 'test 1: 1 of them fail ' >&3
ethernet-parser.py "$data/ethtool-test-fail.log" 2 0 |& tee "$out"
grep 'Ethernet parser tests result is: FAIL' "$out"

echo -n 'test 2: both of them fail ' >&3
ethernet-parser.py "$data/ethtool-test-fail2.log" 2 0 |& tee "$out"
grep 'Ethernet parser tests result is: FAIL' "$out"

echo -n 'test 3: both pass ' >&3
ethernet-parser.py "$data/ethtool-test.log" 2 0 |& tee "$out"
grep 'Ethernet parser tests result is: PASS' "$out"

echo -n 'test 4: no link connection ' >&3
ethernet-parser.py "$data/compulab-test.log" 2 1 |& tee "$out"
grep 'Ethernet parser tests result is: FAIL' "$out"

echo 'ok.' >&3
