#!/bin/bash
set -eu -o pipefail

# Unit test for compatibles.
# Usage: compatibles [keep]
# We keep our temporary folder when `keep' is specified.

# Redirect all output to a log in current folder.
# Keep stdout on fd 3.
bn=$(basename "$0")
log="$bn.log"
exec 3>&1 >"$log" 2>&1
set -x

echo -n 'Testing compatibles... ' >&3
trap 'echo "ERROR! (see $log)" >&3' ERR

# Make sure compatibles is in the path.
me=$(realpath "$0")
here="${me%/*}"
export PATH="$here/..:$PATH"

# Temporary folder.
if [ "${1:-unset}" == keep ]; then
	tmp=$(mktemp -d "$(basename "$0").XXX")
else
	tmp=$(mktemp -d)
	trap 'rm -fr "$tmp"' EXIT
fi

data="$here/data/$(basename "$0")"
out="$tmp/out"

echo -n 'dummy, ' >&3
compatibles "$data/dummy" |& tee "$out"
grep 'dummy,a' "$out"
grep 'dummy,b' "$out"
grep 'dummy,c' "$out"

echo 'ok.' >&3
