#!/bin/bash
set -eu -o pipefail

# Unit test for ethernet-parser.py.
# Usage: test-ethernet [keep]
# We keep our temporary folder when `keep' is specified.

# Redirect all output to a log in current folder.
# Keep stdout on fd 3.
bn=$(basename "$0")
log="$bn.log"
exec 3>&1 >"$log" 2>&1
set -x

echo -n 'Testing ethernet-parser... ' >&3
trap 'echo "ERROR! (see $log)" >&3' ERR

# Make sure ethernet-parser.py is in the path.
me=$(realpath "$0")
here="${me%/*}"
export PATH="$here/..:$PATH"

# Temporary folder.
if [ "${1:-unset}" == keep ]; then
	tmp=$(mktemp -d "$(basename "$0").XXX")
else
	tmp=$(mktemp -d)
	trap 'rm -fr "$tmp"' EXIT
fi

data="$here/data/$(basename "$0")"
out="$tmp/out"

echo -n 'test 1: 1 of them fail' >&3

if ethernet-parser.py "$data/ethtool-test-fail.log" 2 --debug |& tee "$out"; then
	false
fi

grep 'Ethernet parser tests result is: FAIL' "$out"

echo -n ', test 5: two ethernets, 1 of them fail but only requested 1 to pass' >&3
ethernet-parser.py "$data/ethtool-test-fail.log" 1 --debug |& tee "$out"
grep 'Ethernet parser tests result is: PASS' "$out"

echo -n ', test 2: both of them fail' >&3

if ethernet-parser.py "$data/ethtool-test-fail2.log" 2 --debug |& tee "$out"; then
	false
fi

grep 'Ethernet parser tests result is: FAIL' "$out"

echo -n ', test 3: both pass' >&3
ethernet-parser.py "$data/ethtool-test.log" 2 --debug |& tee "$out"
grep 'Ethernet parser tests result is: PASS' "$out"

echo -n ', test 4: no link connection' >&3

if ethernet-parser.py "$data/compulab-test.log" 2 --debug |& tee "$out"; then
	false
fi

grep 'Ethernet parser tests result is: FAIL' "$out"

echo -n ', test 6: too few' >&3

if ethernet-parser.py "$data/ethtool-test.log" 3 |& tee "$out"; then
	false
fi

if grep Traceback "$out"; then
	false
fi

grep 'expected a bigger number of ethernets' "$out"

echo -n ', test 7: unsup' >&3
ethernet-parser.py --debug "$data/ethtool-test-unsup.log" 1 |& tee "$out"
grep 'DEBUG .* Ethtool: device 1, selftest unsupported' "$out"
grep 'DEBUG .* Ping: device 1, PASSED' "$out"
grep 'DEBUG .* match found: .*ethtool.*FAIL.*ping.*PASS' "$out"
grep 'Ethernet parser tests result is: PASS' "$out"

echo ', ok.' >&3
