#!/bin/bash
set -eu -o pipefail

# Unit test for identify.py.
# Usage: test-identify [keep]
# We keep our temporary folder when `keep' is specified.

# Redirect all output to a log in current folder.
# Keep stdout on fd 3.
bn=$(basename "$0")
log="$bn.log"
exec 3>&1 >"$log" 2>&1
set -x

echo -n 'Testing identify... ' >&3
trap 'echo "ERROR! (see $log)" >&3' ERR

# Make sure identify.py is in the path.
me=$(realpath "$0")
here="${me%/*}"
export PATH="$here/..:$PATH"

# Temporary folder.
if [ "${1:-unset}" == keep ]; then
	tmp=$(mktemp -d "$(basename "$0").XXX")
else
	tmp=$(mktemp -d)
	trap 'rm -fr "$tmp"' EXIT
fi

data="$here/data/$(basename "$0")"
out="$tmp/out"

echo -n 'none, ' >&3
identify.py |& tee "$out"
grep Unknown "$out"

echo -n 'ir1.0 bet-0, ' >&3
identify.py --dir "$data/v21.05_0.8_BETA-0" |& tee "$out"
grep 'SystemReady IR v1.0' "$out"

echo -n 'stable debug, ' >&3
a="$tmp/a.log"
b="$tmp/b.log"
identify.py --dir "$data/v21.05_0.8_BETA-0" --debug |& tee "$a"
identify.py --dir "$data/v21.05_0.8_BETA-0" --debug |& tee "$b"
diff -u "$a" "$b"

identify.py --dir "$data/v21.05_0.8_BETA-0" --ebbr-seq |& tee "$out"
grep 'ACS-IR v21.05_0.8_BETA-0' "$out"

echo -n 'ir1.0 bet-1, ' >&3
identify.py --dir "$data/v21.07_0.9_BETA" |& tee "$out"
grep 'SystemReady IR v1.0' "$out"

identify.py --dir "$data/v21.07_0.9_BETA" --ebbr-seq |& tee "$out"
grep 'ACS-IR v21.07_0.9_BETA' "$out"

echo -n 'ir1.2, ' >&3
identify.py --dir "$data/v21.09_1.0" |& tee "$out"
grep 'SystemReady IR v1.2' "$out"

identify.py --dir "$data/v21.09_1.0" --ebbr-seq |& tee "$out"
grep 'ACS-IR v21.09_1.0' "$out"

echo -n 'ir1.2 linux 6.7, ' >&3
identify.py --dir "$data/v24.01_1.0-Linux-v6.7" |& tee "$out"
grep 'SystemReady IR v1.2' "$out"

identify.py --dir "$data/v24.01_1.0-Linux-v6.7" --ebbr-seq |& tee "$out"
grep 'ACS-IR v21.09_1.0' "$out"

identify.py --dir "$data/v24.01_1.0-Linux-v6.7" --known-files |& tee "$out"
grep 'FWTSResults.log from ACS-IR v24.01_1.0-Linux-v6.7' "$out"

echo -n 'sie 1.0, ' >&3
identify.py --dir "$data/v21.10_SIE_REL1.0" |& tee "$out"
grep 'SystemReady SIE v1.0' "$out"

identify.py --dir "$data/v21.10_SIE_REL1.0" --bbsr-seq |& tee "$out"
grep 'SIE ACS v21.10_SIE_REL1.0' "$out"

echo -n 'ir2.0 bet-0, ' >&3
identify.py --dir "$data/v22.06_2.0.0_BETA-0" |& tee "$out"
grep 'SystemReady IR v2.0' "$out"

identify.py --dir "$data/v22.06_2.0.0_BETA-0" --ebbr-seq |& tee "$out"
grep 'ACS-IR v21.09_1.0' "$out"

echo -n 'ir2.0 bet-1, ' >&3
identify.py --dir "$data/v22.10_2.0.0_BETA-1" |& tee "$out"
grep 'SystemReady IR v2.0' "$out"

identify.py --dir "$data/v22.10_2.0.0_BETA-1" --ebbr-seq |& tee "$out"
grep 'ACS-IR v22.10_2.0.0_BETA-1' "$out"

echo -n 'ir2.0 bet-1 + sie, ' >&3
identify.py --dir "$data/v22.10_2.0.0_BETA-1_with_SIE" |& tee "$out"
grep 'SystemReady IR v2.0 with SIE' "$out"

identify.py --dir "$data/v22.10_2.0.0_BETA-1_with_SIE" --ebbr-seq |& tee "$out"
grep 'ACS-IR v22.10_2.0.0_BETA-1 .. v23.09_2.1.0 with SIE' "$out"

echo -n 'ir2.0, ' >&3
identify.py --dir "$data/v23.03_2.0.0" |& tee "$out"
grep 'SystemReady IR v2.0' "$out"

identify.py --dir "$data/v23.03_2.0.0" --ebbr-seq |& tee "$out"
grep 'v23.03_2.0.0' "$out"

echo -n 'ir2.0 linux 6.4, ' >&3
identify.py --dir "$data/v23.03_2.0.0-Linux-v6.4" |& tee "$out"
grep 'SystemReady IR v2.0' "$out"

identify.py --dir "$data/v23.03_2.0.0-Linux-v6.4" --ebbr-seq |& tee "$out"
grep 'v23.03_2.0.0' "$out"

echo -n 'ir2.0 + sie, ' >&3
identify.py --dir "$data/v23.03_2.0.0_with_SIE" |& tee "$out"
grep 'SystemReady IR v2.0 with SIE' "$out"

identify.py --dir "$data/v23.03_2.0.0_with_SIE" --ebbr-seq |& tee "$out"
grep 'ACS-IR v22.10_2.0.0_BETA-1 .. v23.09_2.1.0 with SIE' "$out"

echo -n 'ir 32b 1.2, ' >&3
identify.py --dir "$data/v22.10_IR_32b_0.7_BETA-0" |& tee "$out"
grep 'SystemReady IR 32b v1.2' "$out"

identify.py --dir "$data/v22.10_IR_32b_0.7_BETA-0" --ebbr-seq |& tee "$out"
grep 'ACS-IR v22.10_IR_32b_0.7_BETA-0' "$out"

echo -n 'ir2.1, ' >&3
identify.py --dir "$data/v23.09_2.1.0" |& tee "$out"
grep 'SystemReady IR v2.1' "$out"

identify.py --dir "$data/v23.09_2.1.0" --ebbr-seq |& tee "$out"
grep 'v23.09_2.1.0' "$out"

echo -n 'ir2.1 + sie, ' >&3
identify.py --dir "$data/v23.09_2.1.0_with_SIE" |& tee "$out"
grep 'SystemReady IR v2.1 with SIE' "$out"

identify.py --dir "$data/v23.09_2.1.0_with_SIE" --ebbr-seq |& tee "$out"
grep 'ACS-IR v22.10_2.0.0_BETA-1 .. v23.09_2.1.0 with SIE' "$out"

echo -n 'acs-ir 2.1.1, ' >&3
identify.py --dir "$data/v24.03_2.1.1" |& tee "$out"
grep 'SystemReady IR v2.1' "$out"

identify.py --dir "$data/v24.03_2.1.1" --known-files |& tee "$out"
grep --text 'FWTSResults.log from ACS-IR v24.03_2.1.1' "$out"
grep --text 'BSALinuxResults.log from ACS-IR v24.03_2.1.1' "$out"

echo -n 'sr2.5 acs v24.03, ' >&3
identify.py --dir "$data/v24.03_2.1.0_SR" --sbbr-seq |& tee "$out"
grep 'SR v2.5 with ACS v24.03_2.1.0' "$out"

echo -n 'sr2.5 acs v23.09, ' >&3
identify.py --dir "$data/v23.09_2.0.0_SR" --sbbr-seq |& tee "$out"
grep 'SR v2.5 with ACS v23.09_2.0.0' "$out"


echo -n 'no sie, ' >&3
identify.py --dir "$data/no-SIE" --known-files |& tee "$out"
grep 'BBSR.seq' "$out"
grep 'Unknown' "$out"

echo 'ok.' >&3
