---
name: CI
# yamllint disable-line rule:truthy
on: push

jobs:
  check-job:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make python3 python3-construct python3-yaml \
            python3-chardet python3-jsonschema u-boot-tools python3-requests \
            uuid-runtime python3-packaging device-tree-compiler bsdextrautils \
            python3-pip swig yamllint flake8 git mypy pylint shellcheck \
            python3-rfc3987
          pip3 install --break-system-packages dtschema

      - name: Check
        run: make -k check

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}

        with:
          name: Logs
          path: test-*.log

  doc-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make pandoc texlive-latex-base \
            texlive-latex-recommended texlive-latex-extra

      - name: Generate doc
        run: make doc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4

        with:
          name: Doc
          path: README.pdf
